name: CI

on:
  push:
  pull_request:
    # https://developer.github.com/webhooks/event-payloads/#pull_request
    types: [edited, synchronize]
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        run: |
          npm ci --quiet
          npm install -g danger-plugin-toolbox@1.29.0
          npm run danger
        # if: github.event_name == 'pull_request' && github.event.action == 'edited'
